### ISSUE TITLE
TypeError: Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by Rav-Naz** [mukaschultze/nativescript-windowed-modal#13]
`System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method run failed
System.err: TypeError: Cannot read property 'x' of undefined
System.err:
System.err: StackTrace:
System.err:     Frame: function:'push.../node_modules/nativescript-windowed-modal/modal-stack.js.ModalStack.outsideTap', file:'file:///node_modules\nativescript-windowed-modal\modal-stack.js:40:0
System.err:     Frame: function:'', file:'file:///node_modules\nativescript-windowed-modal\modal-stack.js:22:39
System.err:     Frame: function:'_executeCallback', file:'file:///node_modules\tns-core-modules\ui\gestures\gestures.js:299:0
System.err:     Frame: function:'', file:'file:///node_modules\tns-core-modules\ui\gestures\gestures.js:47:0
System.err:     Frame: function:'invoke', file:'file:///node_modules\tns-core-modules\timer\timer.js:19:30
System.err:     Frame: function:'push.../node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js.ZoneDelegate.invoke', file:'file:///node_modules\nativescript-angular\zone-js\dist\zone-nativescript.js:388:0
System.err:     Frame: function:'push.../node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js.Zone.runGuarded', file:'file:///node_modules\nativescript-angular\zone-js\dist\zone-nativescript.js:151:0
System.err:     Frame: function:'', file:'file:///node_modules\nativescript-angular\zone-js\dist\zone-nativescript.js:129:0
System.err:     Frame: function:'run', file:'file:///node_modules\tns-core-modules\timer\timer.js:23:0
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1109)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1089)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1081)
System.err:     at com.tns.gen.java.lang.Runnable.run(Runnable.java:17)
System.err:     at android.os.Handler.handleCallback(Handler.java:873)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6692)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

### Which platform(s) does your issue occur on?
- Android 9

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.0.2
- Cross-platform modules: 6.0.1
- Runtime(s):
    "tns-android": {"version": "6.0.0"}

- Plugin(s): 
 "dependencies": {
    "@angular/animations": "~8.0.0",
    "@angular/common": "~8.0.0",
    "@angular/compiler": "~8.0.0",
    "@angular/core": "~8.0.0",
    "@angular/forms": "~8.0.0",
    "@angular/http": "~8.0.0-beta.10",
    "@angular/platform-browser": "~8.0.0",
    "@angular/platform-browser-dynamic": "~8.0.0",
    "@angular/router": "~8.0.0",
    "express": "^4.17.1",
    "mariadb": "^2.1.0",
    "mysql": "^2.17.1",
    "mysql2": "^1.6.5",
    "nativescript-angular": "~8.0.0",
    "nativescript-datetimepicker": "^1.2.1",
    "nativescript-email": "^1.5.5",
    "nativescript-feedback": "^1.3.12",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-local-notifications": "^4.0.1",
    "nativescript-permissions": "^1.3.7",
    "nativescript-secure-storage": "^2.6.0",
    "nativescript-svg": "^1.3.7",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-toast": "^2.0.0",
    "nativescript-ui-calendar": "^5.0.0",
    "nativescript-windowed-modal": "^6.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "~6.5.0",
    "sequelize": "^5.10.1",
    "sequelize-typescript": "^1.0.0-alpha.9",
    "tns-core-modules": "6.0.1",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.0.0",
    "@ngtools/webpack": "~8.0.0",
    "@types/node": "^12.6.8",
    "nativescript-dev-webpack": "1.0.1",
    "typescript": "3.4.5"
  },

### Please, tell us how to recreate the issue in as much detail as possible. 
Open and close modal, and immediately re-open the same modal. Keep this process, after few repetition you can get error.

### Is there any code involved? 
[component in repository](https://github.com/Rav-Naz/LSOApp/tree/master/LSOApp/LSOApp/src/app/opiekun/ministrant-dyzury
)

**Comment by mukaschultze** [comment]
I tested this and couldn't reproduce the issue.

One thing that I noticed is this: 
```ts
viewContainerRef: this.uiService.getRootVCRef() ? this.uiService.getRootVCRef() : this.vcRef
```
Have you tried using `viewContainerRef: this.vcRef` directly? Does it keep crashing?

**Comment by Rav-Naz** [comment]
Thank you very much, the crashes are stopped
