### ISSUE TITLE
Background opacity (dimAmount) not working on iOS

### ISSUE THREAD

**Issue by Tyler-V** [mukaschultze/nativescript-windowed-modal#25]
### Which platform(s) does your issue occur on?
- iOS / 13.3

### Is there any code involved? 
```
.modal {
  margin: 20;
  margin-top: 35;
  border-radius: 8;
  horizontal-align: center;
  vertical-align: middle;
  background-color: white;
}

.modal-container {
  padding: 25;
  padding-bottom: 10;
}

```
```
  showMapLayers() {
    const options = {
      viewContainerRef: this.vcRef,
      fullscreen: false,
      dimAmount: 0.5,
    };

    return this.modalDialogService.showModal(MapStylesComponent, options);
  }
```

```
<ModalStack dismissEnabled="true" class="modal-container">
  <StackLayout class="modal">
    <AbsoluteLayout width="100%" height="50" style="border-bottom-color: #DDD; border-bottom-width: 1;">
      <StackLayout orientation="horizontal" width="100%" height="100%">
        <Label text="Map Styles" fontSize="20" fontWeight="bold" width="100%" textAlignment="center" verticalAlignment="center"></Label>
      </StackLayout>
    </AbsoluteLayout>
    <StackLayout class="p-10">
      <StackLayout>
        <Button text="Streets" class="-primary" (tap)="setStyle(MapStyle.MAPBOX_STREETS)"></Button>
        <Button text="Terrain" class="-primary" (tap)="setStyle(MapStyle.OUTDOORS)"></Button>
        <Button text="Satellite" class="-primary" (tap)="setStyle(MapStyle.SATELLITE_STREETS)"></Button>
      </StackLayout>
    </StackLayout>
  </StackLayout>
</ModalStack>

```

![image](https://user-images.githubusercontent.com/3893234/77234343-97ca7a00-6b7b-11ea-9f3a-959cb2bb547a.png)

![image](https://user-images.githubusercontent.com/3893234/77234454-87ff6580-6b7c-11ea-8cbb-56d4be251a55.png)

**Comment by Tyler-V** [comment]
Setting the backgroundColor as transparent on the modal-container allows me to show the background content once again but I'm unable to add an opaque background.

```
<ModalStack dismissEnabled="true" class="modal-container" backgroundColor="transparent">
  <StackLayout class="modal">
  ...
```

![image](https://user-images.githubusercontent.com/3893234/77234559-5c30af80-6b7d-11ea-9648-0d941220a1cb.png)

**Comment by Tyler-V** [comment]
Fixed, https://github.com/mukaschultze/nativescript-windowed-modal/pull/26

**Comment by Tyler-V** [comment]
@mukaschultze @CalebJTSmith @lochstar @edusperoni

**Comment by juanm4** [comment]
Hi, I want give thanks to @Tyler-V for this fix. I am using nativescript vue and I would to know if this merge is going to be done soon. If not, I would like to know if is possible to install this library pointing to @Tyler-V master branch for a temporal fix.

¿Are there something that make that the library in my package.json point to this pull?

Thanks and kind regards!

**Comment by lochstar** [comment]
@juanm4 You can point directly to a git branch in your package.json. [Here's an article](https://medium.com/@jonchurch/use-github-branch-as-dependency-in-package-json-5eb609c81f1a) that may help.

**Comment by juanm4** [comment]
@lochstar Thanks for info, but unfortunately in this library there isn't a package.json in the root path. So, when you try to install `npm install --save Tyler-V/nativescript-windowed-modal#master` it fails.

Any suggestion to fix it?
Thanks!

**Comment by Tyler-V** [comment]
Looks like some regression was introduced in the latest update @mukaschultze @CalebJTSmith @lochstar @edusperoni 

Can we reopen this issue? Or should I make a new one, this is appearing in Android on NS7 now.

```
    showMapLayers() {
        const options = {
            viewContainerRef: this.vcRef,
            animated: false,
            fullscreen: true,
            dimAmount: 0.5,
        };

        return this.modalDialogService.showModal(MapStylesComponent, options);
    }
```

![Screenshot_20210216-164639](https://user-images.githubusercontent.com/3893234/108125564-9bf66480-7076-11eb-8a74-46ad59cae218.png)
