### ISSUE TITLE
Removing/Changing background opacity?

### ISSUE THREAD

**Issue by calebsmithdev** [mukaschultze/nativescript-windowed-modal#4]
I am really liking this setup, but I was curious if there was a way to change the opacity? I am hoping to create a slide-in menu from the bottom (thinking like the Twitter app) and for the overlay to be a bit darker at times.

**Comment by mukaschultze** [comment]
Hi, I'm implementing dim opacity and background color, it'll be available soon.

**Comment by calebsmithdev** [comment]
Awesome! I am very excited to hear that.

**Comment by mukaschultze** [comment]
Version 5.0.4 has been published

You can now pass a `dimAmount` as an argument when showing a modal:

```ts
mainPage.showModal("./modal", {
    context: "I'm the context",
    closeCallback: (response: string) => console.log("Modal response: " + response),
    dimAmount: 0.5 // Sets the alpha of the background dim
} as ExtendedShowModalOptions);
```

`backgroundColor` is also supported now from CSS/XML/HTML, you can leave the `dimAmount` at zero and animate the opacity using this property.

See the [readme](https://github.com/mukaschultze/nativescript-windowed-modal/blob/master/README.md) for usage examples.

**Comment by calebsmithdev** [comment]
I am still a Nativescript-Vue newbie, but I translated the modalview Vue component to also work with your new options. I'm not sure if you can add them to your package or not, but they are here in case anyone wants them for their project. It's a 1:1 with the original, with the exception of the showModal modifications. I saved my file as `ModalPluginVue.js`

```
function _findParentModalEntry(vm) {
  if (!vm) {
    return false
  }

  let entry = vm.$parent
  while (entry && entry.$options.name !== 'ModalEntry') {
    entry = entry.$parent
  }

  return entry
}

export default {
  install(Vue) {
    Vue.mixin({
      created() {
        const self = this
        this.$modal = {
          close(data) {
            const entry = _findParentModalEntry(self)

            if (entry) {
              entry.closeCb(data)
            }
          }
        }
      }
    })

    Vue.prototype.$showModal = function(component, options) {
      const defaultOptions = {
        fullscreen: false,
        animated: true,
        stretched: false,
        dimAmount: 0.5
      }
      // build options object with defaults
      options = Object.assign({}, defaultOptions, options)

      return new Promise(resolve => {
        let resolved = false
        const closeCb = data => {
          if (resolved) return

          resolved = true
          resolve(data)
          modalPage.closeModal()

          // emitted to show up in devtools
          // for debugging purposes
          navEntryInstance.$emit('modal:close', data)
          navEntryInstance.$destroy()
        }

        const navEntryInstance = new Vue({
          name: 'ModalEntry',
          parent: this.$root,
          methods: {
            closeCb
          },
          render: h =>
            h(component, {
              props: options.props
            })
        })
        const modalPage = navEntryInstance.$mount().$el.nativeView
        this.$el.nativeView.showModal(modalPage, {
          context: null,
          closeCallback: closeCb,
          fullscreen: options.fullscreen,
          animated: options.animated,
          stretched: options.stretched,
          dimAmount: options.dimAmount
        })
      })
    }
  }
}
```

Then in your main.js file, you will call 
```
import ModalPlugin from '~/plugins/ModalPluginVue.js'
Vue.use(ModalPlugin)
```
EDIT: All of this is now part of the package! Nice and easy.

**Comment by FranciZ** [comment]
It's slightly unclear how this applies to Angular. In Angular you would normally show the modal by:

```typescript
    const options = {
      viewContainerRef: this.vcRef,
      fullscreen: false,
      context: {
        achievement
      },
      dimAmount: 0
    };

    this.modalService.showModal(ModalAchievementComponent, options);
```

So how does `this.modalService.showModal` apply to `mainPage.showModal` that's in your example.

**Comment by danielnitu** [comment]
> It's slightly unclear how this applies to Angular. In Angular you would normally show the modal by:
> 
> ```ts
>     const options = {
>       viewContainerRef: this.vcRef,
>       fullscreen: false,
>       context: {
>         achievement
>       },
>       dimAmount: 0
>     };
> 
>     this.modalService.showModal(ModalAchievementComponent, options);
> ```
> 
> So how does `this.modalService.showModal` apply to `mainPage.showModal` that's in your example.

I'd also like to know this. Had no success using Angular's ModalDialogService. It opens the default modal. Tried injecting a Page reference in Angular, but it won't accept the 'moduleName' param passed as the modal component.

`this.page.showModal(ModalComponent, options)`

**Comment by edusperoni** [comment]
@danielnitu please refer to the documentation to make sure you're overriding the modal funcion correctly: https://github.com/mukaschultze/nativescript-windowed-modal#typescriptangular

Also ensure you're using nativescript-angular >=7.2.4

**Comment by danielnitu** [comment]
@edusperoni Yes, it was my mistake after all.
The plugin works well, shoutout to all those involved in creating and maintaining it.
